[package]
name = "brainfuck"
version = "0.1.0"
authors = ["miyazakisouya <green-24@outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
